# Dapr Configuration - Production (Oracle OKE)
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: todo-app
spec:
  mtls:
    enabled: true
    sentryAddress: dapr-sentry.dapr-system.svc.cluster.local:443
    controlPlaneTrustDomain: cluster.local
    workloadCertTTL: 24h
    allowedClockSkew: 15m
  metrics:
    enabled: true
  tracing:
    samplingRate: "0.1"
  features:
    - name: SchedulerReminders
      enabled: true
